# Generated by Django 5.0.2 on 2024-03-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='bridePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridePhoto', models.ImageField(upload_to='images/bride')),
            ],
        ),
        migrations.RenameModel(
            old_name='photos',
            new_name='protraitPhoto',
        ),
    ]
